sudo: false
language: java
jdk:
  - oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -fr $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"
- "export ORG_GRADLE_PROJECT_bladePluginVersion=${BLADE_PLUGIN_VERSION}"

after_failure:
  - cat build/idea-sandbox/system/log/idea.log

env:
  # - IDEA_VERSION="IU-2019.1" PHP_PLUGIN_VERSION="191.6183.95" BLADE_PLUGIN_VERSION="191.6183.95" not working 'No such property: artifactName for class: org.jetbrains.intellij.jbre.JbreResolver'
  - IDEA_VERSION="IU-2018.3.5" PHP_PLUGIN_VERSION="183.4886.46" BLADE_PLUGIN_VERSION="183.3795.24"
  - IDEA_VERSION="IU-2018.2.4" PHP_PLUGIN_VERSION="182.4505.42" BLADE_PLUGIN_VERSION="182.3911.19"
  - IDEA_VERSION="IU-2018.1" PHP_PLUGIN_VERSION="181.4203.565" BLADE_PLUGIN_VERSION="181.4203.565"
  - IDEA_VERSION="IU-2017.3.5" PHP_PLUGIN_VERSION="173.4301.34" BLADE_PLUGIN_VERSION="173.4127.29"

script:
- "./gradlew check verifyPlugin buildPlugin"
